// NOTE: This structure is intended to match the backend hike entity schema in Firebase.

export const hikeEntities = {
  "tunnel-bench-loop": {
    hikeId: "tunnel-bench-loop",
    title: "Tunnel Bench Loop (Hoodoos)",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.tripadvisor.ca%2FShowUserReviews-g154911-d10820346-r599541775-Hoodoos_Trail-Banff_Banff_National_Park_Alberta.html&psig=AOvVaw2J0raeSM3G6dlveanVnrZv&ust=1745397958535000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPjkm56g64wDFQAAAAAdAAAAABAE",
    location: "Banff",
    province: "AB",
    difficulty: "Moderate",
    distance: 5,
    distanceUnit: "km",
    timeEstimateMinutes: 108,
    elevation: 66,
    elevationUnit: "m",
    status: "open",
  },
  "valley-of-five-lakes": {
    hikeId: "valley-of-five-lakes",
    title: "Valley of Five Lakes",
    image:
      "https://beckerschalets.com/wp-content/uploads/2020/07/five-lakes-2.jpg",
    location: "Jasper National Park",
    province: "AB",
    difficulty: "Moderate",
    distance: 4.5,
    distanceUnit: "km",
    timeEstimateMinutes: 150,
    elevation: 66,
    elevationUnit: "m",
    status: "open",
  },
  "valley-of-five-lakes-2": {
    hikeId: "valley-of-five-lakes-2", // Ensure this matches the key
    title: "Valley of Five Lakes - Extended Loop",
    image:
      "https://beckerschalets.com/wp-content/uploads/2020/07/five-lakes-2.jpg",
    location: "Jasper National Park",
    province: "AB",
    difficulty: "Hard",
    distance: 8.0,
    distanceUnit: "km",
    timeEstimateMinutes: 240,
    elevation: 120,
    elevationUnit: "m",
    status: "open",
  },
  "ha-ling-peak": {
    hikeId: "ha-ling-peak",
    title: "Ha Ling Peak",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Ha-Ling-aerial.jpg/1920px-Ha-Ling-aerial.jpg",
    location: "Bow Valley Wildland Provincial Park",
    province: "AB",
    difficulty: "Hard",
    distance: 7.4,
    distanceUnit: "km",
    timeEstimateMinutes: 210,
    elevation: 763,
    elevationUnit: "m",
    status: "open",
  },
  "ha-ling-peak-2": {
    hikeId: "ha-ling-peak-2",
    title: "Ha Ling Peak - Ridge Trail",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Ha-Ling-aerial.jpg/1920px-Ha-Ling-aerial.jpg",
    location: "Bow Valley Wildland Provincial Park",
    province: "AB",
    difficulty: "Moderate",
    distance: 5.0,
    distanceUnit: "km",
    timeEstimateMinutes: 150,
    elevation: 500,
    elevationUnit: "m",
    status: "open",
  },
  "johnston-canyon": {
    hikeId: "johnston-canyon",
    title: "Johnston Canyon",
    image:
      "https://outandacross.com/wp-content/uploads/2022/01/johnston-canyon-hike-in-banff-np-1024x768.jpg",
    location: "Banff National Park",
    province: "AB",
    difficulty: "Easy",
    distance: 5.0,
    distanceUnit: "km",
    timeEstimateMinutes: 120,
    elevation: 120,
    elevationUnit: "m",
    status: "open",
  },
  "johnston-canyon-2": {
    hikeId: "johnston-canyon-2",
    title: "Johnston Canyon - Upper Falls",
    image:
      "https://outandacross.com/wp-content/uploads/2022/01/johnston-canyon-hike-in-banff-np-1024x768.jpg",
    location: "Banff National Park",
    province: "AB",
    difficulty: "Moderate",
    distance: 7.0,
    distanceUnit: "km",
    timeEstimateMinutes: 180,
    elevation: 200,
    elevationUnit: "m",
    status: "open",
  },
  "lake-louise-teahouse": {
    hikeId: "lake-louise-teahouse",
    title: "Lake Louise Teahouse",
    image:
      "https://cdn.sanity.io/images/lr9tta69/production/f05e7cd7431d57a20074e6a1f8c2533fe226da1e-640x480.jpg",
    location: "Banff National Park",
    province: "AB",
    difficulty: "Moderate",
    distance: 10.6,
    distanceUnit: "km",
    timeEstimateMinutes: 240,
    elevation: 400,
    elevationUnit: "m",
    status: "open",
  },
  "lake-louise-teahouse-2": {
    hikeId: "lake-louise-teahouse-2",
    title: "Lake Louise Teahouse - Scenic Route",
    image:
      "https://cdn.sanity.io/images/lr9tta69/production/f05e7cd7431d57a20074e6a1f8c2533fe226da1e-640x480.jpg",
    location: "Banff National Park",
    province: "AB",
    difficulty: "Hard",
    distance: 12.0,
    distanceUnit: "km",
    timeEstimateMinutes: 300,
    elevation: 500,
    elevationUnit: "m",
    status: "open",
  },
  "plain-of-six-glaciers": {
    hikeId: "plain-of-six-glaciers",
    title: "Plain of Six Glaciers",
    image:
      "https://www.travelbanffcanada.com/wp-content/uploads/2020/09/The-Lake-Louise-Lakeshore-Trail-and-the-plain-of-six-glaciers-hike-share-the-same-trail-960x720.jpg",
    location: "Lake Louise",
    province: "AB",
    difficulty: "Hard",
    distance: 14.6,
    distanceUnit: "km",
    timeEstimateMinutes: 300,
    elevation: 587,
    elevationUnit: "m",
    status: "open",
  },
  "plain-of-six-glaciers-2": {
    hikeId: "plain-of-six-glaciers-2",
    title: "Plain of Six Glaciers - Extended Trail",
    image:
      "https://www.travelbanffcanada.com/wp-content/uploads/2020/09/The-Lake-Louise-Lakeshore-Trail-and-the-plain-of-six-glaciers-hike-share-the-same-trail-960x720.jpg",
    location: "Lake Louise",
    province: "AB",
    difficulty: "Hard",
    distance: 18.0,
    distanceUnit: "km",
    timeEstimateMinutes: 400,
    elevation: 700,
    elevationUnit: "m",
    status: "open",
  },
  "plain-of-six-glaciers-3": {
    hikeId: "plain-of-six-glaciers-3",
    title: "Plain of Six Glaciers - Scenic Route",
    image:
      "https://www.travelbanffcanada.com/wp-content/uploads/2020/09/The-Lake-Louise-Lakeshore-Trail-and-the-plain-of-six-glaciers-hike-share-the-same-trail-960x720.jpg",
    location: "Lake Louise",
    province: "AB",
    difficulty: "Moderate",
    distance: 12.0,
    distanceUnit: "km",
    timeEstimateMinutes: 240,
    elevation: 400,
    elevationUnit: "m",
    status: "open",
  },
  "plain-of-six-glaciers-4": {
    hikeId: "plain-of-six-glaciers-4",
    title: "Plain of Six Glaciers - Easy Route",
    image:
      "https://www.travelbanffcanada.com/wp-content/uploads/2020/09/The-Lake-Louise-Lakeshore-Trail-and-the-plain-of-six-glaciers-hike-share-the-same-trail-960x720.jpg",
    location: "Lake Louise",
    province: "AB",
    difficulty: "Easy",
    distance: 8.0,
    distanceUnit: "km",
    timeEstimateMinutes: 180,
    elevation: 200,
    elevationUnit: "m",
    status: "open",
  },
  "plain-of-six-glaciers-5": {
    hikeId: "plain-of-six-glaciers-5",
    title: "Plain of Six Glaciers - Family Friendly Route",
    image:
      "https://www.travelbanffcanada.com/wp-content/uploads/2020/09/The-Lake-Louise-Lakeshore-Trail-and-the-plain-of-six-glaciers-hike-share-the-same-trail-960x720.jpg",
    location: "Lake Louise",
    province: "AB",
    difficulty: "Easy",
    distance: 6.0,
    distanceUnit: "km",
    timeEstimateMinutes: 120,
    elevation: 100,
    elevationUnit: "m",
    status: "open",
  },
  "throat-of-the-world": {
    hikeId: "throat-of-the-world",
    title: "Throat of the World",
    image: "https://images.uesp.net/5/55/SR-place-Throat_of_the_World.jpg",
    location: "The Pale",
    province: "Skyrim",
    difficulty: "Hard",
    distance: 120,
    distanceUnit: "m",
    timeEstimateMinutes: 360,
    elevation: 1430,
    elevationUnit: "m",
    status: "open",
  },
};
