services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
    - ./src:/app/src
    - /app/node_modules
    env_file:
      - .env
    
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true

