services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
    stdin_open: true
    tty: true
    command: npm run dev